root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bin/server ./cmd/api/main.go"
bin = "tmp/bin/server"

stop_on_error = true
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
log = "air.log"

[screen]
clear_on_rebuild = true
keep_scroll = true
