name: "enterprise-backend-template-dev"
services:
  # Main Redis instance.
  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

  # PostgreSQL database.
  db:
    image: postgres:16.4
    shm_size: 128mb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: winens
      POSTGRES_PASSWORD: winens123123
      POSTGRES_DB: project_dev

  # Minio S3 storage.
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: winens
      MINIO_ROOT_PASSWORD: winens123123

  # Dummy SMTP server.
  mockmail:
    image: soulteary/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  minio_data:
    driver: local
